export const TOGGLE_MUTE = "TOGGLE_MUTE";
export const SET_AUDIO = "SET_AUDIO";
export const SET_TIMER = "SET_TIMER";

export const SET_TIME_END_NOTIFICATION = "SET_TIME_END_NOTIFICATION";
export const SET_TIMER_ON_BROWSER = "SET_TIMER_ON_BROWSER";
export const SET_WEB_NOTIICATION = "SET_WEB_NOTIICATION";

export const SET_TOTAL_SESSION = "SET_TOTAL_SESSION";
export const SET_CURRENT_SESSION = "SET_CURRENT_SESSION";
export const SET_COUNTDOWN = "SET_COUNTDOWN";

export const TOGGLE_IMAGE = "TOGGLE_IMAGE";
